#!/bin/bash
TITLE=聊齋誌異
cd $TITLE
MISSING_XCANGJIE_IN_XTEXT=$(node ../checkxfonts.js)
if [[ -n $MISSING_XCANGJIE_IN_XTEXT ]]; then
   echo $MISSING_XCANGJIE_IN_XTEXT
   cp ../xtext.html index.html
   cp ../xtext.js .
   live-server
   exit 1
fi   
echo $(node ../gen2spx.js) > last_chapter.txt
#../all_make_cover 001
cd audio
cp $HOME/my-ms-translator/officialdom/temp/key .
cp $HOME/my-ms-translator/officialdom/temp/region .
../../all_make_audio 001
rm *wav
rm *log
rm key
rm region
cd ..
#../all_make_youtube 001
$HOME/send2hanley
